apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service-account.yaml
  - test-pod.yaml
  - test-pod-python.yaml

commonLabels:
  app.kubernetes.io/part-of: workload-identity-test
